# Generated by Django 3.1.4 on 2020-12-06 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planista', '0003_auto_20201206_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='nip',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
