# Generated by Django 3.1.4 on 2020-12-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planista', '0006_event_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='add_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='opinion',
            name='add_date',
            field=models.DateTimeField(default=None),
        ),
    ]
