# Generated by Django 3.1.4 on 2020-12-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planista', '0007_auto_20201207_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='private',
        ),
    ]
