# Generated by Django 3.1.4 on 2021-01-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planista', '0009_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firm',
            new_name='Company',
        ),
    ]
