# Generated by Django 3.1.4 on 2021-01-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planista', '0010_auto_20210109_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
