# Generated by Django 3.1.4 on 2021-01-26 17:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planista', '0012_auto_20210109_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='firm',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/images/default.png', storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
    ]
